### ISSUE TITLE
Get a Development-setup from scratch from Debian Bookworm 12

### ISSUE THREAD

**Issue by webafrancois** [mawoka-myblock/ClassQuiz#318]
### Which component is affected?

run_tests.sh firt run

### Did the issue occur at ClassQuiz.de, or on a self-hosted instance?

On ClassQuiz.de

### How can the issue be reproduced?

From a fresh Debian Bookworm, I installed : 
* python3.11
* node 18
* npm 
* pnpm (from pip)
* docker
* caddy (from stable repositories)

I git clone from master branch on a folder of a classquiz's user (who can run docker command)

I run : 
`pipenv install -d``
works fine
`cd frontend && pnpm i`
works fine too

But : 
`./run_tests.sh +`
fails.

### Describe the bug (with screenshots if possible)

`./run_tests.sh +`
returns : 

```
./run_tests.sh +
Unable to find image 'redis:alpine' locally
alpine: Pulling from library/redis
661ff4d9561e: Pull complete 
963a98d2b6c2: Pull complete 
dddcc6acb2ed: Pull complete 
ff0ac71727e7: Pull complete 
7959e5ad61f4: Pull complete 
d767cfa2fc09: Pull complete 
4f4fb700ef54: Pull complete 
64281ae03186: Pull complete 
Digest: sha256:a3e82d34456f5d012dcbf542b564c39697c14dc4225cf3d29b3278fca041ad15
Status: Downloaded newer image for redis:alpine
e79c03d6bcd2a018bc1b8a8db40f0c6f9c16895c18ad502e6f40147eaa989503
Unable to find image 'getmeili/meilisearch:v0.28.0' locally
v0.28.0: Pulling from getmeili/meilisearch
8663204ce13b: Pull complete 
d13bc4bdd1b5: Pull complete 
f8a648d81fd7: Pull complete 
0033a2ddd0e1: Pull complete 
877bb1e3a033: Pull complete 
Digest: sha256:94bb999a7c7afa81a64872186b553699213614f705824dd73909a2556fd9b132
Status: Downloaded newer image for getmeili/meilisearch:v0.28.0
d561cdb4f708c7f2cb6d4931f186c40bb9f8d00f224460961858751d4fa98bfe
classquiz_db_data
Unable to find image 'postgres:latest' locally
latest: Pulling from library/postgres
1f7ce2fa46ab: Pull complete 
8a0c088137b8: Pull complete 
11be68f68a2e: Pull complete 
19f13c4e1d96: Pull complete 
43187fdc5ebc: Pull complete 
a84cb0803492: Pull complete 
b50a897e2632: Pull complete 
7bc6d5552c52: Pull complete 
c8161286a3f1: Pull complete 
e36f0ab546af: Pull complete 
c2a71678092b: Pull complete 
7c23bdcac538: Pull complete 
16648961c661: Pull complete 
Digest: sha256:a2282ad0db623c27f03bab803975c9e3942a24e974f07142d5d69b6b8eaaf9e2
Status: Downloaded newer image for postgres:latest
cffb6887722f131d9dc62e920aeedcb28bf6fbf9381f9c64b1e60d0aa92ab543
Traceback (most recent call last):
  File "/home/classquiz/.local/share/virtualenvs/ClassQuiz-yHaRkT7z/bin/alembic", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/classquiz/.local/share/virtualenvs/ClassQuiz-yHaRkT7z/lib/python3.11/site-packages/alembic/config.py", line 632, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/home/classquiz/.local/share/virtualenvs/ClassQuiz-yHaRkT7z/lib/python3.11/site-packages/alembic/config.py", line 626, in main
    self.run_cmd(cfg, options)
  File "/home/classquiz/.local/share/virtualenvs/ClassQuiz-yHaRkT7z/lib/python3.11/site-packages/alembic/config.py", line 603, in run_cmd
    fn(
  File "/home/classquiz/.local/share/virtualenvs/ClassQuiz-yHaRkT7z/lib/python3.11/site-packages/alembic/command.py", line 385, in upgrade
    script.run_env()
  File "/home/classquiz/.local/share/virtualenvs/ClassQuiz-yHaRkT7z/lib/python3.11/site-packages/alembic/script/base.py", line 582, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/home/classquiz/.local/share/virtualenvs/ClassQuiz-yHaRkT7z/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
    module = load_module_py(module_id, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/classquiz/.local/share/virtualenvs/ClassQuiz-yHaRkT7z/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/classquiz/ClassQuiz/migrations/env.py", line 7, in <module>
    from classquiz.db.models import metadata
  File "/home/classquiz/ClassQuiz/classquiz/__init__.py", line 11, in <module>
    from classquiz.config import settings
  File "/home/classquiz/ClassQuiz/classquiz/config.py", line 88, in <module>
    pool = redis_lib.ConnectionPool().from_url(settings().redis)
                                               ^^^^^^^^^^
  File "/home/classquiz/ClassQuiz/classquiz/config.py", line 85, in settings
    return Settings()
           ^^^^^^^^^^
  File "pydantic/env_settings.py", line 39, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 6 validation errors for Settings
mail_address
  field required (type=value_error.missing)
mail_password
  field required (type=value_error.missing)
mail_username
  field required (type=value_error.missing)
mail_server
  field required (type=value_error.missing)
mail_port
  field required (type=value_error.missing)
secret_key
  field required (type=value_error.missing)
```

### Device

Desktop

### Operating System

Linux Debian Bookworm

### Browser

Actually none

**Comment by webafrancois** [comment]
So, I create a .env in the root project, and it works better...
`./run_tests.sh +`
And it works better.
And I try the Front-dev-server exposable
cd frontend && API_URL=http://localhost:8080 pnpm dev --host 0.0.0.0
I can see from my local network.

But should I run some other services, because "register" is broken when I submit a new user creation : 
'Unexpected error!
There was the good old unexpected error!'

Should I run all the other services to have a complete ClassQuiz running?
Should I just run :
```
pipenv run uvicorn classquiz:app --reload --proxy-headers
cd frontend && API_URL=http://localhost:8080 pnpm dev
```
I added `--host 0.0.0.0` to have a network interface on the 3000 port.

I don't understand what should I run to have a complete dev env.

Thanks a lot for your patience.

**Comment by webafrancois** [comment]
Note : Finally, I found a solution to have a Dev setup with Docker like [this post](#317)

**Comment by mawoka-myblock** [comment]
You need to make sure that Caddy is running, too.

> So, I create a .env in the root project, and it works better... `./run_tests.sh +` And it works better. And I try the Front-dev-server exposable
> 
> ```
> cd frontend && API_URL=http://localhost:8080 pnpm dev --host 0.0.0.0
> ```
> 
> I can see from my local network.
> 
> But should I run some other services, because "register" is broken when I submit a new user creation :
> 
> > 'Unexpected error!
> > There was the good old unexpected error!'
> 
> Should I run all the other services to have a complete ClassQuiz running? Should I just run :
> 
> ```
> pipenv run uvicorn classquiz:app --reload --proxy-headers
> cd frontend && API_URL=http://localhost:8080 pnpm dev
> ```
> 
> I added `--host 0.0.0.0` to have a network interface on the 3000 port.
> 
> I don't understand what should I run to have a complete dev env.
> 
> Thanks a lot for your patience.
